export const FILMS_ADD_COMMENT = 'FILMS_ADD_COMMENT';
export const USERS_GET_SUBSCRIBED = 'USERS_GET_SUBSCRIBED';
export const USERS_UNSUBSCRIBED = 'USERS_UNSUBSCRIBED';
export const USERS_PHOTO_ADD_COMMENT = 'USERS_PHOTO_ADD_COMMENT';
export const POSTS_ADD_COMMENT = 'POSTS_ADD_COMMENT';
export const POSTS_INCREASE_RATING = 'POSTS_INCREASE_RATING';
export const POSTS_DECREASE_RATING = 'POSTS_DECREASE_RATING';
export const POSTS_ADD_ANSWER = 'POSTS_ADD_ANSWER';
